version: '3.8'
services:
  loadtest:
    image: ${SHASTA_CDK_ECR_REPO_URI}:shasta-devenv
    command: /bin/bash -c "npx ts-node src/lib/pubsub/loadtest.ts > /tmp/loadtest_$$(date +%Y-%m-%d-%H%M%S)_$${HOSTNAME}_$${RANDOM}.log 2>&1"
    environment:
      CODECOMMIT_REPO_SSH: ${CODECOMMIT_REPO_SSH}
      CODECOMMIT_STREAM_NAME: ${CODECOMMIT_STREAM_NAME}
      SHASTA_CDK_ECR_REPO_URI: ${SHASTA_CDK_ECR_REPO_URI}
      SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
      BOOTSTRAP_BROKERS: ${BOOTSTRAP_BROKERS}
      MULTICAST_STREAM_NAME: ${MULTICAST_STREAM_NAME}
      CODECOMMIT_REPO_HTTPS: ${CODECOMMIT_REPO_HTTPS}
    volumes:
      - /tmp:/tmp
    working_dir: /root/repo/dev/shasta  # Set the working directory here
