version: '3.8'
services:
  loadtest:
    image: ${SHASTA_CDK_ECR_REPO_URI}:shasta-devenv  # Dynamically use the ECR repo URI and tag from environment variables
    command: npx ts-node src/lib/pubsub/loadtest.ts
    environment:
      CODECOMMIT_REPO_SSH: ${CODECOMMIT_REPO_SSH}  # Use environment variables from the host
      CODECOMMIT_STREAM_NAME: ${CODECOMMIT_STREAM_NAME}
      SHASTA_CDK_ECR_REPO_URI: ${SHASTA_CDK_ECR_REPO_URI}
      SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
      BOOTSTRAP_BROKERS: ${BOOTSTRAP_BROKERS}
      MULTICAST_STREAM_NAME: ${MULTICAST_STREAM_NAME}
      CODECOMMIT_REPO_HTTPS: ${CODECOMMIT_REPO_HTTPS}
    volumes:
      - /tmp:/tmp  # Mount /tmp directory as in docker_run.sh
